x=int(input("Enter 1st No="))
y=int(input("Enter 2nd No="))
print('x + y =',x+y)
print('x - y =',x-y)
print('x * y =',x*y)
print('x / y =',x/y)
print('x // y =',x//y)
print('x ** y =',x**y) #x^y(**=power)